"""Agregar qr_token a personas

Revision ID: bedad08b3801
Revises: a5856493a240
Create Date: 2025-12-30 15:06:39.384544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bedad08b3801'
down_revision = 'a5856493a240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_token', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['qr_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('qr_token')

    # ### end Alembic commands ###
